### ISSUE TITLE
Ipv6 Support

### ISSUE THREAD

**Issue by DSponge** [linuxserver/docker-duckdns#15]
Could you add ipv6?

Thanks

**Comment by aptalca** [comment]
Unfortunately, I have no ipv6 capability so I can't do any testing, troubleshooting or dev work. PRs are welcome ;)

**Comment by kaxiorek** [comment]
I could do that, as I have IPv6 and have changed your docker to update my DuckDNS with it.
Sadly as my lack on docker knowledge i do not know if interface br0 is always "global" one and I do not know how to handle possibility of changing this interface in docker templates

**Comment by aptalca** [comment]
Post what you have done and we'll take a look

**Comment by kaxiorek** [comment]
You can see it here. 
https://github.com/kaxiorek/docker-duckdns/commit/f8fc7a29b37d47d6b3993bb467662d3aea326305

I've added output from first commad that i have used in comments.
