### ISSUE TITLE
Where to report abuse?

### ISSUE THREAD

**Issue by sshcli** [linuxserver/docker-duckdns#28]
**Where to report abuse?**

I need to know where can I report abuse of the duckdns service.

For example:
This person is copying content from my website (Copyright infringement) without my authorization:
http://vjacheslavmuzrh2000.duckdns.org/article702.php

Please help me to stop this immediately.

**Comment by thelamer** [comment]
You look up their actual ip address and report it to their abuse contact https://www.arin.net/reference/materials/abuse/

This is a docker container with a script in it , totally the incorrect platform for these questions

**Comment by sshcli** [comment]
Sorry @thelamer 
I'm desperate and frustrated and couldn't find any place where to report the issue
I won't do it again.
