### ISSUE TITLE
Add INTERVAL to allow for checkin > 5 minutes

### ISSUE THREAD

**Issue by rweckhoff** [linuxserver/docker-duckdns#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Allow for user determined IP address update time (e.g. 60 minutes)
## Current Behavior

Update time is 5 minutes

**Comment by xr09** [comment]
@rweckhoff this is kind of a hack but you can replace `/etc/crontabs/abc` with whatever frequency you prefer.

Create a local file custom-crontab with this: (you can tune it at will, I'm using every 1 hour here, [check docs](https://crontab.guru/every-1-hour))

```bash
0 * * * * /app/duck.sh 2>&1
```

Then replace the stock frequency with yours:

```yml
volumes:
  - ./custom-crontab:/etc/crontabs/abc
```
