### ISSUE TITLE
TZ variable not working on arm32v7-latest

### ISSUE THREAD

**Issue by kai8ilw0rld** [linuxserver/docker-duckdns#36]
- I noticed this issue on the arm32v7-latest image (arm32v7-3a3f0388-ls70). 
- Logs showed "something went wrong.."
- While looking more into it I noticed the time inside the container was incorrect even though I had the correct TZ environment variable 
- TZ=America/Los_Angeles
- Fixed it by reverting to an older version (arm32v7-ce996582-ls65) of the image which worked great

------------------------------

## Expected Behavior
Date inside container on version arm32v7-ce996582-ls65: Sat Mar 27 07:06:43  2021

## Current Behavior
Date inside the container:  Wed Dec 31 16:00:00 PST 1969

## Environment
**OS: Raspberry Pi OS Lite
**CPU architecture:** arm32
**How docker service was installed: from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
docker run -d \
  --name=duckdns \
  -e PUID=1000 \
  -e PGID=1000  \
  -e TZ=America/Los_Angeles \
  -e SUBDOMAINS=****** \
  -e TOKEN=************* \
  -e LOG_FILE=true \
  -v /home/pi/docker/duckdns:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/duckdns:arm32v7-latest

## Docker logs

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-config: executing... 
Retrieving subdomain and token from the environment variables
g will be output to file
Something went wrong, please check your settings  Thu Feb 4 07:06:40 PST 138072
[cont-init.d] 40-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by j0nnymoe** [comment]
You should notice this in the logs:
```@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 
 
Your DockerHost is most likely running an outdated version of libseccomp
 
 
To fix this, please visit https://docs.linuxserver.io/faq#libseccomp
 
 
Some apps might not behave correctly without this
 
 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@```
If not... ^ that's your issue.
