### ISSUE TITLE
Consider Chomping Whitespace when using FILE__ Environment Variables

### ISSUE THREAD

**Issue by stellarpower** [linuxserver/docker-duckdns#40]
I am using podman, and sharing my DuckDNS token with a simple bind mount. I erase all newlines at the end of the file, but my text editor has (silently) still added one on save. It thus comes into the configs as such:
```termninal
root@6e2b4f16f191:/app# cat duck.conf 
SUBDOMAINS="..." TOKEN="12345678-abcd-abcd-12ab-132435465768
"
root@6e2b4f16f191:/app# 
```
The closing quote has come after the newline.

Whilst technically my token is of improper format, and whilst I'm sidestepping the secrets process at this point in time:
- It seems not unreasonable that new users may leave a dangling newline and not be aware of the potential problems of this
- Given that the FILE__ variables are to replace environment variables anyway, in most if not all cases, I am presuming that a newline in the variable would not be acceptable, and thus, chomping whitespace automatically shouldn't result in undefined behaviour
- If the above is a reasonable assumption, it seems sensible to sanitise the input earlier rather than allow crashes down the line, even if the error is on my part in this case
- The error message could be cryptic for some:
```
...
curl: (3) URL using bad/illegal format or missing URL
Something went wrong, please check your settings Fri Jun 18 19:52:10 UTC 2021
The response returned was:
⏎
...
```
The configuration is sourced in `/app/duck.sh` and Bash will presumably complain of a syntax error upon sourcing, and abort there, which has propagated through.

## Expected Behavior
1. One of the entrypoint scripts should check for valid format and complain that the subdomain and/or token are invalid
  - Possibly outputting these to console
2. The app script could source the configuration with more error checking
3. My main point is that it's not great that the configuration file contains invalid syntax, we ought to stop before reaching that point, and so I would recommend that if it would be deemed reasonable and well-defined to assume that no environment variables should contain trailing whitespace like that and to chomp newlines and/or any leading/trailing whitespace for most environment values passed into the containers, then it would also be reasonable to do so on the files, and am proposing consideration of a policy like across ls.io images.

## Steps to Reproduce
1. I am using podman over docker on this project. Am warning in case it effects reproducability, but I doubt it.
2. `echo "12345678-abcd-abcd-12ab-132435465768" >/tmp/token`
3. `podman run --rm -it -v '/tmp/token:/DuckDNS.token' -e "SUBDOMAINS=mysubdomain" -e "FILE__TOKEN=/DuckDNS.token" ghcr.io/linuxserver/duckdns cat /app/duck.conf` 
4. Note the file output in the terminal.
5. Note also that this is hard to detect in the terminal - many utilities add a trailing newline and `cat /tmp/token` doesn't display a blank newline in my fish terminal:
```fish
~> echo "12345678-abcd-abcd-12ab-132435465768" > /tmp/token
~> cat /tmp/token 
12345678-abcd-abcd-12ab-132435465768
~> echo  -n "12345678-abcd-abcd-12ab-132435465768" > /tmp/token
~> cat /tmp/token
12345678-abcd-abcd-12ab-132435465768⏎                                                                   
~>
```
Fish has been helpful and displayed the carriage return symbol to inidcate that the shell has added the newline, but when the trailing newline is present, it is more subtle.

## Environment
**OS:** Ubuntu-based (focal)
**CPU architecture:** amd64
**How docker service was installed:** Using podman-compose and podman originally. Image pulled from ghcr.io as in examples using compose file.

**Comment by aptalca** [comment]
We will not modify the variables passed for various reasons.

It is your responsibility to make sure your vars (or files) have the right content.

The behavior is meant to mimick how docker secrets are used. The docker secret info page, which is linked in our readmes, shows how to correctly create the secrets (files) without the trailing newline via printf.
