### ISSUE TITLE
duckdns setup on raspi 4

### ISSUE THREAD

**Issue by 9Z4A** [linuxserver/docker-duckdns#42]
I am new to this can someone give me a step by step way to solve this, please. Thank you

Anthony
kj4rwz@gmail.com

![main nissue](https://user-images.githubusercontent.com/68905827/134719972-a1153fe9-8d17-4016-958e-b003d2bf0faf.jpg)

**Comment by aptalca** [comment]
That has nothing to do with our docker image. Our instructions are in the readme
