### ISSUE TITLE
[Feature Request]: Ability to use a single DuckDNS updater with multiple User Accounts

### ISSUE THREAD

**Issue by LostOnTheLine** [linuxserver/docker-duckdns#50]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I recently had a new user come into my home. They use `DuckDNS` as well. 
I have had to import their settings into my **NGINX Proxy Manager** to get their stuff to work alongside my own. 
I was wondering if there could be a way to combine the `DuckDNS Updater` to work with more than 1 account. 
I don't want to merge our DuckDNSes as they will only be here for 6 months. 
I know this is an unusual use-case, but I'm sure other people will have other reasons to need it as well.

## Current Behavior

`DuckDNS` updater only works with a single user account
## Alternatives Considered

We are currently using 2 separate machines running 2 separate instances of `DuckDNS Updater`. 
This is working fine, but has a few negatives. 
1. Their system is not on all the time, so any redirects from **NGINX**, handled by my **NGINX**, will be set to display an _"Offline"_ page when not available. If the DNS updates while they are offline their pages will be going somewhere else that we have no control of which can be a security concern.
2. There may be an issue if our systems are connecting at the same time to update
3. Though small the resource usage of running 2 separate instances is more than running a single instance

**Comment by aptalca** [comment]
Not worth the effort as it's an edge case, and running 2 instances of duckdns is totally fine even on the same machine as there is a random delay. The resource usage is negligible as it's just running cron on a ~5 min timer for a single curl api call
