### ISSUE TITLE
[BUG] Container Docker Duckdns, curl failed to verify the legitimacy of the server

### ISSUE THREAD

**Issue by pganansia** [linuxserver/docker-duckdns#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi guys,
Since few month I have this message in the log of docker/duckdns :
`2023-08-01T07:36:52.628042911Z curl: (60) SSL: no alternative certificate subject name matches target host name 'www.duckdns.org'
2023-08-01T07:36:52.628131488Z More details here: https://curl.se/docs/sslcerts.html
2023-08-01T07:36:52.628156343Z 
2023-08-01T07:36:52.628168652Z curl failed to verify the legitimacy of the server and therefore could not
2023-08-01T07:36:52.628180344Z establish a secure connection to it. To learn more about this situation and
2023-08-01T07:36:52.628191873Z how to fix it, please visit the web page mentioned above.
2023-08-01T07:36:52.639332682Z Something went wrong, please check your settings Tue Aug  1 07:36:52 UTC 2023
2023-08-01T07:36:52.639374999Z The response returned was:
2023-08-01T07:36:52.639400250Z 
`

I found this issue about amazon in https://github.com/k3s-io, issue #7680.
In the dialog, I found the command : curl -vks and I tried with `curl -vks www.duckdns.org`

The result is :
`root@duckdns:/# curl -vk https://www.duckdns.org
* processing: https://www.duckdns.org
*   Trying 35.183.231.248:443...
* Connected to www.duckdns.org (35.183.231.248) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=Georgia; O=Crawford & Company; CN=*.aomsettlement.ca
*  start date: Mar 23 00:00:00 2023 GMT
*  expire date: Mar 22 23:59:59 2024 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo ECC Organization Validation Secure Server CA
*  SSL certificate verify result: self-signed certificate in certificate chain (19), continuing anyway.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: www.duckdns.org]
* h2 [:path: /]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET / HTTP/2
> Host: www.duckdns.org
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/2 200 
< date: Tue, 01 Aug 2023 07:55:09 GMT
< content-type: text/html
< content-length: 617
< last-modified: Fri, 23 Jul 2021 22:31:24 GMT
< accept-ranges: bytes
< etag: "046e5771280d71:0"
< server: Microsoft-IIS/10.0
< x-powered-by: ASP.NET
< 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>AOM Settlement</title>
        <base href="/"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" type="image/x-icon" href="favicon.ico"/>
    <link rel="stylesheet" href="styles.7e5419dbe767a2f76f6d.css"></head>

    <body>
        <core-root></core-root>
    <script src="runtime.63f65fa3296259fc0471.js" defer></script><script src="polyfills.2058ae9b600c9ca6751c.js" defer></script><script src="main.8b31e8662d63b27e93af.js" defer></script></body>

* Connection #0 to host www.duckdns.org left intact`

We can see that curl is trying to check the url with this "subject: C=US; ST=Georgia; O=Crawford & Company; CN=***.aomsettlement.ca**" which has nothing to do with Duckdns.

If I simply use the command : curl -vks www.duckdns.org, the result is : 
`root@duckdns:/# curl -vks www.duckdns.org
* processing: www.duckdns.org
*   Trying 35.183.231.248:80...
* Connected to www.duckdns.org (35.183.231.248) port 80
> GET / HTTP/1.1
> Host: www.duckdns.org
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: awselb/2.0
< Date: Tue, 01 Aug 2023 07:58:37 GMT
< Content-Type: text/html
< Content-Length: 134
< Connection: keep-alive
< Location: https://www.duckdns.org:443/
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
* Connection #0 to host www.duckdns.org left intact`

I am not an expert in SSL certificates and curl but if someone can help me, it will be appreciate.
Rgds

### Expected Behavior

Stopping having this error message, signifying that the server is verified

### Steps To Reproduce

Just start the container and look at the log

### Environment

```markdown
- OS: Linux 6.1.0-0.deb11.7-amd64
- How docker service was installed:

Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:45 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3'
services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    hostname: duckdns
    networks:
      - swag_default
    dns:
      - 172.20.0.254
    environment:
      - PUID=1006
      - PGID=100
      - TZ=Etc/FR
      - SUBDOMAINS=xxxxx,yyyyy,zzzzz
      - TOKEN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

      - LOG_FILE=true
    volumes:
      - /mnt/CRU1DATA1/AppData/Duckdns/config:/config
    restart: unless-stopped
    
networks:
    swag_default:
        external: true
```

### Container logs

```bash
2023-08-01T07:36:52.628042911Z curl: (60) SSL: no alternative certificate subject name matches target host name 'www.duckdns.org'
2023-08-01T07:36:52.628131488Z More details here: https://curl.se/docs/sslcerts.html
2023-08-01T07:36:52.628156343Z 
2023-08-01T07:36:52.628168652Z curl failed to verify the legitimacy of the server and therefore could not
2023-08-01T07:36:52.628180344Z establish a secure connection to it. To learn more about this situation and
2023-08-01T07:36:52.628191873Z how to fix it, please visit the web page mentioned above.
2023-08-01T07:36:52.639332682Z Something went wrong, please check your settings Tue Aug  1 07:36:52 UTC 2023
2023-08-01T07:36:52.639374999Z The response returned was:
2023-08-01T07:36:52.639400250Z
```

**Comment by aptalca** [comment]
Likely dns issue on your end. Their ssl cert indeed contains that address as a san

**Comment by pganansia** [comment]
Thanks a lot.
I found that I was having a bad IP address in my dnsproxyserver container.
Rgds.
