### ISSUE TITLE
[BUG] linuxserver/duckdns:arm32v7-latest image has OS/ARCH linux/amd64

### ISSUE THREAD

**Issue by philippdoersek** [linuxserver/docker-duckdns#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest duckdns image cannot be pulled on 32-bit arm architectures such as an older raspberry pi as the linuxserver/duckdns:arm32v7-latest image at hub.docker.com has OS/ARCH linux/amd64 (digest: sha256:45b4de29ef06ed62c2165e72b8e4badb80d0d77524ed7af01e7fa44b5e8c2578, see https://hub.docker.com/layers/linuxserver/duckdns/arm32v7-latest/images/sha256-45b4de29ef06ed62c2165e72b8e4badb80d0d77524ed7af01e7fa44b5e8c2578?context=explore).

### Expected Behavior

Any arm32v7 image should have OS/ARCH linux/arm/v7.

### Steps To Reproduce

See https://hub.docker.com/layers/linuxserver/duckdns/arm32v7-latest/images/sha256-45b4de29ef06ed62c2165e72b8e4badb80d0d77524ed7af01e7fa44b5e8c2578?context=explore

### Environment

```markdown
- OS:
- How docker service was installed:
N/A
```

### CPU architecture

arm64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by Roxedus** [comment]
This is done intentionally, to point at that it wont be the latest release.
https://www.linuxserver.io/blog/a-farewell-to-arm-hf
