### ISSUE TITLE
[FEAT] Local IP option

### ISSUE THREAD

**Issue by gabrielecalvo** [linuxserver/docker-duckdns#71]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Have the ability to set the internal ip instead of the external one.

### Reason for change

For some home-lab cases using dns certificates it would be nice to be able to set the local ip instead of the external ip.

### Proposed code change

Something like `UPDATE_IP=local-ipv4` could do the trick.
Maybe just adding the following extra elif-branch in https://github.com/linuxserver/docker-duckdns/blob/master/root/app/duck.sh
```bash
elif [ "${UPDATE_IP}" = "local-ipv4" ]; then
        echo "Detecting local IPv4 via hostname command"
        IPV4=$(hostname -I)
        RESPONSE=$(curl -sS --max-time 60 "https://www.duckdns.org/update?domains=${SUBDOMAINS}&token=${TOKEN}&ip=${IPV4}")
```

**Comment by j0nnymoe** [comment]
I feel this is something that doesn't need to be automated and you could do the same by just manually setting your duckdns address to a local IP. Or if you're needing both internal and external, you'd use duckdns.
