### ISSUE TITLE
[FEAT] Log IP address that was sent to duckdns.org

### ISSUE THREAD

**Issue by petermicuch** [linuxserver/docker-duckdns#72]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to be able to see IP address that was sent to duckdns.org in the log of the container. It would be fine to only add this extended logging upon setting of ENV variable  (i.e. `EXTENDED_LOGING_ENABLED`) for extending logging.

### Reason for change

This would allow me to detect when the change of IP has happened and could relate it to small hiccups that are happening to instance of a service that I run in my network.

### Proposed code change

change in `https://github.com/linuxserver/docker-duckdns/blob/master/root/app/duck.sh`

```sh
echo "Your IP was updated at $(date). IPV4 is ${IPV4} and IPV6 is ${IPV6}"
```
I would provide PR to only log IPV4 or IPV6 or both based on configured option of `UPDATE_IP` variable.

**Comment by aptalca** [comment]
We'll take that into consideration but in the meantime, duckdns website shows the last changed date for each subdomain when logged in.

**Comment by petermicuch** [comment]
@aptalca - thank you for giving me hint for immediate chance to track my issue. 

I still think that having this also locally visible in my cluster would be nice. I could also run a job myself, but repeating same steps does not make much sense to me.
Even better would be if such log is printed when change is detected (this does not need to survive restarts of the container of course). Log stating that the IP was updated every 5 minutes is not bringing much of new information. Especially when there is log upon failure of update in the same interval. So having log written only when actual change has happened or when an error happened would be more beneficial. At least in my opinion.

**Comment by homerr** [comment]
We've made some enhancements to the container that take care of this one.

Enjoy!
