### ISSUE TITLE
[FEAT] Make the intervall a parameter so we can configure it

### ISSUE THREAD

**Issue by Asghan86** [linuxserver/docker-duckdns#78]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please change the fixed 5 minute intervall to a configurable parameter.
5 minutes is way too often from my point of view

### Reason for change

If everyone uses this container and pulls/pushs/checks every 5 minutes this creates unnecessary load for the duckdns hoster.

### Proposed code change

none. I am not a coder, just user.

**Comment by aptalca** [comment]
5 minutes is what duckdns recommends.

They don't all hit at the same time. There is random jitter built in.
