### ISSUE TITLE
[Feature] Option to modify the update interval

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/docker-duckdns#8]
I think the 5 minutes update interval is unnecessary, therefore an option to modify it would be awesome.

**Comment by aptalca** [comment]
It's the suggested update interval by duckdns: http://duckdns.org/install.jsp

It's such a small ping that I don't think it's worth it to add a parameter to be honest. But I'll think about it.

**Comment by sparklyballs** [comment]
i'm gonna close this as we're using the recommended update interval
